/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.9.0
 *
 * Project: 'M55_HE.Debug+AE722F80F55D5LS' 
 * Target:  'Debug+AE722F80F55D5LS' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"



#endif /* RTE_COMPONENTS_H */
